---
- name: Deploy Your Node.js Application with Nodemon
  hosts: nodejs_servers
  become: yes

  tasks:
    - name: Copy application files excluding node_modules
      synchronize:
        src: "/var/lib/jenkins/workspace/nodeJenkins"
        dest: "/home/thyler/nodejenkins"
        delete: yes
        recursive: yes
        rsync_opts:
          - "--exclude=node_modules/"
      become: no

    - name: Install dependencies
      command: npm install
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

    - name: Ensure nodemon is installed
      npm:
        name: nodemon
        global: yes

    - name: Stop running node process (if any)
      shell: pkill -f "node index.js"
      ignore_errors: yes
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

    - name: Start the application with nodemon
      command: nodemon index.js
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

- name: Finished
  hosts: nodejs_servers
  become: yes
  tasks:
    - name: Ansible finished
      command: echo Deployed
