---
- name: Deploy Your Node.js Application
  hosts: nodejs_servers
  become: yes

  tasks:
    - name: Copy application files excluding node_modules
      synchronize:
        src: "/var/lib/jenkins/workspace/nodeJenkins"
        dest: "/home/thyler/nodejenkins"
        delete: yes
        recursive: yes
        rsync_opts:
          - "--exclude=node_modules/"
      become: no




    - name: Install dependencies
      command: npm install
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

    - name: Stop running node process
      command: kill $(pgrep -f "node index.js")
      ignore_errors: yes
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins
      
      become: yes

    - name: Start the application
      command: node index.js
      async: 604800 #the server will run for one week aftereach build
      poll: 0
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

    #- name: Start Node.js application in the background
    #  shell: "nohup node index.js > /dev/null 2>&1 &"

- name: Finished
  hosts: nodejs_servers
  become: yes
  tasks:
    - name: Ansible finished
      command: echo Deployed
