---
- name: Deploy Your Node.js Application
  hosts: nodejs_servers
  become: yes

  tasks:
    - name: Copy application files excluding node_modules
      synchronize:
        src: "/var/lib/jenkins/workspace/nodeJenkins"
        dest: "/home/thyler/nodejenkins"
        delete: yes
        recursive: yes
        rsync_opts:
          - "--exclude=node_modules/"
      become: no

    - name: Install dependencies
      command: npm install
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

    - name: Ensure PM2 is installed
      npm:
        name: pm2
        global: yes

    - name: Stop running node process with PM2
      command: pm2 stop index
      ignore_errors: yes
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

    - name: Start the application with PM2
      command: pm2 start -f index.js --name "nodejenkins"
      args:
        chdir: /home/thyler/nodejenkins/nodeJenkins

    #- name: Start Node.js application in the background
    #  shell: "nohup node index.js > /dev/null 2>&1 &"

- name: Finished
  hosts: nodejs_servers
  become: yes
  tasks:
    - name: Ansible finished
      command: echo Deployed
