---
- name: Install Node.js and npm
  hosts: nodejs_servers
  become: yes

  tasks:
    - name: Check if package lists are updated
      stat:
        path: /var/lib/apt/lists/lock
      register: apt_lists_lock

    - name: Update package lists
      apt:
        update_cache: yes
      when: apt_lists_lock.stat.exists == false

    - name: Check if Node.js is installed
      command: node -v
      register: node_version
      ignore_errors: true

    - name: Install Node.js
      apt:
        name: nodejs
        state: present
      when: node_version.rc != 0

    - name: Check if npm is installed
      command: npm -v
      register: npm_version
      ignore_errors: true

    - name: Install npm
      apt:
        name: npm
        state: present
      when: npm_version.rc != 0

- name: Deploy Port Forwarding Service
  hosts: nodejs_servers
  become: yes

  tasks:
    - name: Copy systemd service file
      template:
        src: nodejenkins.service.j2
        dest: /etc/systemd/system/nodejenkins.service

    - name: Enable the service
      command: systemctl enable nodejenkins

    - name: Start the service
      command: systemctl start nodejenkins

